### ISSUE TITLE
Busybox ash segfaults on 'ls' after creating many files

### ISSUE THREAD

**Issue by agkaminski** [phoenix-rtos/phoenix-rtos-project#890] opened 2023-10-18 08:12 UTC
```
root@?:/dev/test # ls
root@?:/dev/test # i=0
root@?:/dev/test # while true; do touch $i; i=$(($i+1)); done
^C
root@?:/dev/test # ls
0    12   141  163  185  206  228  25   271  293  314  336  358  40   62   84
1    120  142  164  186  207  229  250  272  294  315  337  359  41   63   85
10   121  143  165  187  208  23   251  273  295  316  338  36   42   64   86
100  122  144  166  188  209  230  252  274  296  317  339  360  43   65   87
101  123  145  167  189  21   231  253  275  297  318  34   361  44   66   88
102  124  146  168  19   210  232  254  276  298  319  340  362  45   67   89
103  125  147  169  190  211  233  255  277  299  32   341  363  46   68   9
104  126  148  17   191  212  234  256  278  3    320  342  364  47   69   90
105  127  149  170  192  213  235  257  279  30   321  343  365  48   7    91
106  128  15   171  193  214  236  258  28   300  322  344  366  49   70   92
107  129  150  172  194  215  237  259  280  301  323  345  367  5    71   93
108  13   151  173  195  216  238  26   281  302  324  346  368  50   72   94
109  130  152  174  196  217  239  260  282  303  325  347  369  51   73   95
11   131  153  175  197  218  24   261  283  304  326  348  37   52   74   96
110  132  154  176  198  219  240  262  284  305  327  349  370  53   75   97
111  133  155  177  199  22   241  263  285  306  328  35   371  54   76   98
112  134  156  178  2    220  242  264  286  307  329  350  372  55   77   99
113  135  157  179  20   221  243  265  287  308  33   351  373  56   78
114  136  158  18   200  222  244  266  288  309  330  352  374  57   79
115  137  159  180  201  223  245  267  289  31   331  353  375  58   8
116  138  16   181  202  224  246  268  29   310  332  354  376  59   80
117  139  160  182  203  225  247  269  290  311  333  355  38   6    81
118  14   161  183  204  226  248  27   291  312  334  356  39   60   82
119  140  162  184  205  227  249  270  292  313  335  357  4    61   83

Exception: 3 #Prefetch
 r0=00000000  r1=00000000  r2=00000001  r3=00047c08
 r4=00000001  r5=00000000  r6=00000046  r7=000059e8
 r8=0000229c  r9=00000002 r10=00002304  fp=00002318
 ip=00000000  sp=c019aef4  lr=0002b59d  pc=00047c14
psr=00000010 dfs=00000000 dfa=00000000 ifs=0000000f
ifa=00047c14

Exception: 3 #Prefetch
 r0=00000000  r1=00000000  r2=00000001  r3=00047c08
 r4=00000001  r5=00000000  r6=00000046  r7=000059e8
 r8=0000229c  r9=00000002 r10=00002304  fp=00002318
 ip=00000000  sp=c019aef4  lr=0002b59d  pc=00047c14
psr=00000010 dfs=00000000 dfa=00000000 ifs=0000000f
ifa=00047c14

in thread 68, process "/bin/ash" (PID: 53)
Segmentation fault
```
after that it will segfault after every next command. Restarting `ash` fixes the issue.

This problem occurs on both jffs2 and dummyfs, so seems fs independent.

**Comment by jmaksymowicz** [comment] 2024-02-08 14:25
I can confirm this happens on `armv7a9-zynq7000-qemu`, but I couldn't reproduce it on `ia32-generic-qemu`.

Interestingly, after restarting `ash` listing the directory with these files no longer causes segfaults.

**Comment by jmaksymowicz** [comment] 2024-02-09 14:02
After more diagnosis:
* Problem happens with any applet marked as `APPLET_NOFORK` - these include `mkdir`, `whoami`, `dirname`, etc. 
  * Except for applets built into `ash`, for example `echo`.
* Problem happens only when the applet above is interrupted with `^C` - if another applet such as `sleep` is interrupted the problem doesn't occur.
* Problem seems to happen only when an environment variable is set within the loop.
* This may be a known, ongoing bug within `ash`: https://git.busybox.net/busybox/tree/shell/ash.c?h=1_36_stable#n10530 The comment seems to describe these exact conditions (`APPLET_NOFORK` and setting environment variables)
  * Additionally, in the newer version of Busybox that I linked there's a comment ```Signals (^C) can't interrupt here. Otherwise we can mangle stdio or malloc internal state.```
* Setting `CONFIG_FEATURE_SH_NOFORK` to `n` will cause all non-builtin applets to fork, which fixes this problem but reduces performance.

**Closed as completed** 2024-02-09 16:22 UTC
