### ISSUE TITLE
Fscanf/sscanf/vsscanf/vfscanf floating point problems

### ISSUE THREAD

**Issue by maska989** [phoenix-rtos/phoenix-rtos-project#604] opened 2023-02-14 11:11 UTC
**1. Floating Points Problems**
   -
 - **All errors occur when floating points value are used in **fscanf/sscanf/vfscanf/vsscanf** on ia32-generic-qemu**

 - To reproduce issue copy following code:
```c
#include <stdio.h>

int main(void)
{
	
	char value[] ="123.123";
	float value_copy;
	static FILE *src;
	src = fopen("test","w+");
	fwrite("123.123",1,sizeof(value),src);
	fputc('\n', src);
	fflush(src);
	rewind(src);
	fscanf(src,"%f",&value_copy);
	printf("\nValue of fscanf %f\n",value_copy);
	fclose(src);

}
```
  - Tested on ia32-generic-qemu
![Screenshot from 2023-02-13 14-51-58](https://user-images.githubusercontent.com/49757239/218475866-2e3946b3-8f9d-4715-abf3-f30fad01ccd3.png)

**Comment by gerard5** [comment] 2023-02-17 10:13
@maska989 The issue is `open` from the beginning, it was not a `draft` issue, a solution was created for it, so why was the title of the problem that concerned a specific thing changed to the generalized form instead of creating another separate issue addressing the next problem  ?

**Comment by maska989** [comment] 2023-02-17 10:34
@gerard5 Didn't meant to do any kind of problem i will separate this in different issues and this one will back to original form. Once again sorry for disruption.

**Comment by gerard5** [comment] 2023-02-17 12:29
@maska989 please verify if the provided solution https://github.com/phoenix-rtos/libphoenix/pull/230 resolves the problem addressed by the current issue topic. From my side it looks like your test after applying the aforementioned PR successfully passes the test provided by you. I compared the result with my host machine:

on ia32-generic (qemu):
![2023-02-17-130554_353x172_scrot](https://user-images.githubusercontent.com/141153/219650397-5bc0658e-b0b7-468d-a5a9-43c542db7385.png)

on host:
![2023-02-17-132058_770x149_scrot](https://user-images.githubusercontent.com/141153/219652346-c34f8e54-16a8-4c58-a8f8-f79a74f3f3a3.png)

**Comment by gerard5** [comment] 2023-02-18 10:32
All fixes for this issue have been merged into master. (https://github.com/phoenix-rtos/phoenix-rtos-project/commit/1db5b2d284ddab504c82f06953b0ae2984aeb4cc):
  > stdio/scanf: Add `%[aefgAEG]` conversions
  > stdio/scanf: Fix `%z` length modifier
  > stdlib/strtod: Fix handling of negative values

**Closed by gerard5** 2023-02-18 10:32 UTC
Labels: libphoenix
