### ISSUE TITLE
`strtod()`, `strtof()`, `strtold()` doesn't convert correctly  hexadecimal value from string

### ISSUE THREAD

**Issue by mateusz-bloch** [phoenix-rtos/phoenix-rtos-project#703] opened 2023-04-25 10:28 UTC
When the string to be converted by `strtod()`, `strtof()`, `strtold()` has a hexadecimal value, the conversion does not proceed correctly
- Code to reproduction:

```
#include <stdio.h>
#include <stdlib.h>

int main (void)
{
	char str[] = "0X1.FFFFFEP-127";
	float strtof_output = strtof(str, NULL);
	double strtod_output = strtod(str, NULL);
	long double strtold_output = strtold(str, NULL);

	printf("%f\n", strtof_output);
	printf("%lf\n", strtod_output);
	printf("%Lf\n", strtold_output);
	
	return 0;
}
```

- Outcome from ia32-generic:

![image](https://user-images.githubusercontent.com/116297248/234249197-b78ac8b1-7498-4b37-95ec-22ff0afa54dd.png)

- Outcome from host-generic:

![image](https://user-images.githubusercontent.com/116297248/234249234-8c3abc9e-677c-4a6f-bef8-0c9493808b11.png)

**Comment by Darchiv** [comment] 2024-07-05 18:47
Duplicate of https://github.com/phoenix-rtos/phoenix-rtos-project/issues/657

**Closed by Darchiv** 2024-07-05 18:47 UTC
Labels: libphoenix
