### ISSUE TITLE
psh: executing psh using `sysexec` and then running `exit` causes an exception

### ISSUE THREAD

**Issue by damianloew** [phoenix-rtos/phoenix-rtos-project#273] opened 2021-12-22 11:28 UTC
Tested on ia32-generic target (qemu). The problem doesn't occur on `armv7m7-imxrt106x`.

![Screenshot from 2021-12-22 12-28-09](https://user-images.githubusercontent.com/77304431/147086052-c0cd8ebb-0329-47b9-9b5c-fc5ae55f9c89.png)

The problem also appears, when executing psh with multiple arguments:

![Screenshot from 2021-12-22 13-27-37](https://user-images.githubusercontent.com/77304431/147093021-c92c403f-d493-4919-8a73-32ee1e34b012.png)

Same problem in the `hm` command:

![Screenshot from 2021-12-22 13-32-47](https://user-images.githubusercontent.com/77304431/147093386-1a88ffa1-eebc-41aa-af15-3ad6d63eac7c.png)

Propably there is something wrong with the `spawnSyspage` syscall.

**Comment by agkaminski** [comment] 2021-12-22 15:09
This issue is caused by executing programs from syspage - both sysexec and hm execute from syspage.
This causes object -1 to be passed to exec and consequently to process_load().
process_load() maps data section as NEEDS_COPY, but for object -1 (physical memory) this flag is effectively ignored (by design).

IMHO there are two solutions:
- Never execute object -1 - create memory object before executing from syspage,
- Copy data segment in process_load manually for case of object -1

**Comment by agkaminski** [comment] 2021-12-22 15:12
Dirty fix: Change else if(...) to else here: https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/4e89fbccfa73e749c7944841f4d4c802010c3e49/vm/map.c#L624

Might break fork() in a very bad way (if e.g. driver has mapped some physical memory of a device)

**Comment by agkaminski** [comment] 2023-06-20 10:34
As the dirty fix has been merged I'm closing this issue as solved

**Closed by agkaminski** 2023-06-20 10:34 UTC
Labels: psh, utils

**Comment by damianloew** [comment] 2023-06-20 10:46
Yeah, seems to be resolved. Thanks!
